apiVersion: v1
kind: Service
metadata:
  name: kubelet
  namespace: monitoring
  labels:
    k8s-app: kubelet
    release: prometheus
spec:
  ports:
    - name: http-metrics
      port: 10255
      targetPort: 10255
  selector:
    component: kubelet
