from prometheus_client import Counter, Histogram

# 1. AI Pipeline duration
PIPELINE_DURATION = Histogram(
    "storesense_pipeline_duration_seconds",
    "Time taken for the full analysis pipeline to run",
    buckets=[1.0, 2.0, 5.0, 10.0, 20.0, 30.0, 60.0, 120.0, float("inf")]
)

# 2. Gemini API latency
GEMINI_LATENCY = Histogram(
    "storesense_gemini_api_latency_seconds",
    "Latency of Gemini API calls in seconds",
    labelnames=["model", "status"]
)

# 3. Agent execution duration
AGENT_DURATION = Histogram(
    "storesense_agent_execution_duration_seconds",
    "Duration of agent node execution in seconds",
    labelnames=["agent_name", "status"]
)

# 4. Request throughput (overall/api)
REQUESTS_TOTAL = Counter(
    "storesense_requests_total",
    "Total HTTP requests received",
    labelnames=["method", "endpoint", "http_status"]
)

# 5. Successful analyses
ANALYSIS_SUCCESS = Counter(
    "storesense_analysis_success_total",
    "Total successful store analyses completed",
    labelnames=["store_url"]
)

# 6. Failed analyses
ANALYSIS_FAILURE = Counter(
    "storesense_analysis_failure_total",
    "Total failed store analyses",
    labelnames=["store_url", "error_type"]
)

# 7. Fallback count
LLM_FALLBACK_COUNT = Counter(
    "storesense_llm_fallback_total",
    "Number of LLM fallback events",
    labelnames=["from_model", "to_model", "type"]
)

# 8. LLM Prompt Tokens
LLM_PROMPT_TOKENS = Counter(
    "storesense_llm_prompt_tokens_total",
    "Total input tokens sent to LLM models",
    labelnames=["model"]
)

# 9. LLM Completion Tokens
LLM_COMPLETION_TOKENS = Counter(
    "storesense_llm_completion_tokens_total",
    "Total output tokens generated by LLM models",
    labelnames=["model"]
)

# 10. LLM Cost USD
LLM_COST_USD = Counter(
    "storesense_llm_cost_usd_total",
    "Total estimated cost of LLM model API requests in USD",
    labelnames=["model"]
)

