apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubelet-sm
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      k8s-app: kubelet
  endpoints:
    - port: http-metrics
      path: /metrics/cadvisor
      interval: 15s
