apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-server-sm
  namespace: default
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  endpoints:
    - port: https
      path: /metrics
      interval: 15s
