apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-servicemonitor
  namespace: default
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: nginx-proxy
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
